export const SHOP_DETAILS_REQUEST="SHOP_DETAILS_REQUEST";
export const SHOP_DETAILS_SUCCESS="SHOP_DETAILS_SUCCESS";
export const SHOP_DETAILS_FAIL="SHOP_DETAILS_FAIL";

export const SHOP_LIST_REQUEST='SHOP_LIST_REQUEST';
export const SHOP_LIST_SUCCESS='SHOP_LIST_SUCCESS';
export const SHOP_LIST_FAIL='SHOP_LIST_FAIL';


